services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - DB_CONNECTION=koch:password@tcp(db:3306)/MoneyWeight?timeout=60s
    depends_on:
      - db
    networks:
      - app-network
    restart: always
    entrypoint: ["/bin/sh", "-c", "sleep 180 && ./api-server"]  # Increased to 3 minutes

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=MoneyWeight
      - MYSQL_USER=koch
      - MYSQL_PASSWORD=password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
