services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - DB_CONNECTION=koch:password@tcp(db:3306)/MoneyWeight
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: on-failure:5  # Retry 5 times if it fails

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=MoneyWeight
      - MYSQL_USER=koch
      - MYSQL_PASSWORD=password
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "koch", "-p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
